stages:
  - build
  - test
  - upload

build-docker-image:
  stage: build
  image: docker:latest
  script:
    - echo "Check the ruby version, then build some Ruby project files:"
    - docker build -t app .

test-docker-image:
  stage: test
  image: docker:latest
  script:
    - docker build -t app .
    - docker run -d -p 80:80 app
    - curl localhost:80

publish:
  stage: upload
  script:
    - echo "If the files are built successfully, publish files with a different command:"
