stages:
  - build
  - test
  - upload

build-docker-image:
  stage: build
  image: docker:latest
  script:
    - echo "Check the ruby version, then build some Ruby project files:"
    - docker build -t app:v1 .

test-docker-image:
  stage: test
  script:
    - echo "If the files are built successfully, test some files with one command:"

publish:
  stage: upload
  script:
    - echo "If the files are built successfully, publish files with a different command:"
